import "./viewDreams.css";
import { useState, useContext, useEffect } from "react";
import { UserContext } from "../components/userContext.jsx";
import ReactMarkdown from "react-markdown";

export function ViewDreams() {
	// const baseURL = 'http://localhost:4000';
	const { user } = useContext(UserContext);
	const [dreams, setDreams] = useState([]);
	// these are example dream entries generated by chatGBT
	// the api should return a list called listOfDreams which contains json objects that look like the examples
	// fyi the default userId is set to 1 just because log in and userIds have not been generated. Check userContext.jsx for info on that
	const sampleDreams = [
		{
			nightId: "1",
			dreamEntry:
				"I was flying over a city made entirely of glass. The streets sparkled under a purple sky, and everyone moved in slow motion.",
			sleepAmount: 7.5,
			date: "2025-04-06",
		},
		{
			nightId: "2",
			dreamEntry:
				"I was being chased by a giant rubber duck through a supermarket. Every aisle led to a different country.",
			sleepAmount: 6,
			date: "2025-03-29",
		},
		{
			nightId: "3",
			dreamEntry:
				"I met a talking cat who gave me a riddle to solve before I could enter a castle made of clouds.",
			sleepAmount: 8,
			date: "2025-03-15",
		},
		{
			nightId: "4",
			dreamEntry:
				"I was at a concert where the band used vegetables as instruments. The carrot trumpet was surprisingly good.",
			sleepAmount: 5.5,
			date: "2025-04-01",
		},
		{
			nightId: "5",
			dreamEntry:
				"I kept reliving the same day over and over, except each time the people around me turned into animals.",
			sleepAmount: 7,
			date: "2025-03-31",
		},
	];

	const getDreams = async () => {
		const response = await fetch(`/api/${user}`);
		if (!response.ok) {
			alert("something went wrong when getting your dream entries!");
			return;
		}
		const data = await response.json();
		setDreams(data.listOfDreams);
		console.log(data.listOfDreams);
	};

	const deleteDream = async (nightID) => {
		console.log(nightID);
		const response = await fetch(`/api/${user}/${nightID}`, {
			method: "DELETE",
		});
		if (response.ok) {
			setDreams((prevDreams) =>
				prevDreams.filter((dream) => dream._id !== nightID),
			);
			console.log("deleted dream entry:" + nightID);
		} else {
			alert("something went wrong when deleting your dream entry!");
		}
	};

	useEffect(() => {
		//setDreams(sampleDreams); // this is for setting dreams to example list, comment out when testing api
		getDreams(); // uncomment this when trying to get dream entries from the api
	}, []);

	return (
		<div class="left-padding">
			<h1>Your Dream Notebook</h1>
			{dreams.length === 0 ? (
				<div>
					<p>No Dreams Found</p>
					<p>
						Click "Create Dream" in the top right to log your first
						dream!
					</p>
				</div>
			) : (
				dreams.map((dream) => (
					<div key={dream.nightId} className="view-dream-container">
						<p>
							<div className="dream-markdown">
								<strong>Dream:</strong>{" "}
								<ReactMarkdown breaks>
									{dream.dreamEntry}
								</ReactMarkdown>
							</div>
						</p>
						<p>
							<strong>Slept:</strong> {dream.sleepAmount} hours
						</p>
						<p>
							<strong>Date:</strong>{" "}
							{new Date(dream.date).toLocaleDateString()}
						</p>
						<button
							className="del-dream-bttn"
							onClick={() => deleteDream(dream._id)}
						>
							Delete
						</button>
					</div>
				))
			)}
		</div>
	);
}

export default ViewDreams;
