import "./viewDreams.css";
import { useState, useContext, useEffect } from "react";
import { UserContext } from "../components/userContext.jsx";
import ReactMarkdown from "react-markdown";
import dayjs from "dayjs";
import {
	AreaChart,
	Area,
	XAxis,
	YAxis,
	Tooltip,
	CartesianGrid,
	ResponsiveContainer,
} from "recharts";

export function ViewDreams() {
	// const baseURL = 'http://localhost:4000';
	const { user } = useContext(UserContext);
	const [dreams, setDreams] = useState([]);
	const [showStats, setShowStats] = useState(false);
	const [totalDreams, setTotalDreams] = useState("");
	const [totalSleep, setTotalSleep] = useState("");
	const [avgSleep, setAvgSleep] = useState("");
	// these are example dream entries generated by chatGBT
	// the api should return a list called listOfDreams which contains json objects that look like the examples
	// fyi the default userId is set to 1 just because log in and userIds have not been generated. Check userContext.jsx for info on that
	const sampleDreams = [
		{
			nightId: "1",
			dreamEntry:
				"I was flying over a city made entirely of glass. The streets sparkled under a purple sky, and everyone moved in slow motion.",
			sleepAmount: 7.5,
			date: "2025-04-06",
		},
		{
			nightId: "2",
			dreamEntry:
				"I was being chased by a giant rubber duck through a supermarket. Every aisle led to a different country.",
			sleepAmount: 6,
			date: "2025-03-29",
		},
		{
			nightId: "3",
			dreamEntry:
				"I met a talking cat who gave me a riddle to solve before I could enter a castle made of clouds.",
			sleepAmount: 8,
			date: "2025-03-15",
		},
		{
			nightId: "4",
			dreamEntry:
				"I was at a concert where the band used vegetables as instruments. The carrot trumpet was surprisingly good.",
			sleepAmount: 5.5,
			date: "2025-04-01",
		},
		{
			nightId: "5",
			dreamEntry:
				"I kept reliving the same day over and over, except each time the people around me turned into animals.",
			sleepAmount: 7,
			date: "2025-03-31",
		},
	];

	const getDreams = async () => {
		const response = await fetch(`/api/${user}`);
		if (!response.ok) {
			alert("something went wrong when getting your dream entries!");
			return;
		}
		const data = await response.json();

		// sorting the list in descending order
		const list = data.listOfDreams.sort(
			(a, b) => new Date(b.date) - new Date(a.date),
		);

		// collecting stats about dream health
		const total = list.length;
		const sleep = list.reduce((sum, d) => sum + d.sleepAmount, 0);
		const avg = total > 0 ? (sleep / total) : 0;
		setTotalDreams(total);
		setTotalSleep(sleep);
		setAvgSleep(avg);

		setDreams(list);
		console.log(data.listOfDreams);
	};

	const deleteDream = async (nightID) => {
		console.log(nightID);
		const response = await fetch(`/api/${user}/${nightID}`, {
			method: "DELETE",
		});
		if (response.ok) {
			setDreams((prevDreams) =>
				prevDreams.filter((dream) => dream._id !== nightID),
			);
			console.log("deleted dream entry:" + nightID);
		} else {
			alert("something went wrong when deleting your dream entry!");
		}
	};

	useEffect(() => {
		//setDreams(sampleDreams); // this is for setting dreams to example list, comment out when testing api
		getDreams(); // uncomment this when trying to get dream entries from the api
	}, []);

	// get list of properly formatted list of date and dreams in left to right format
	const chartData = [...dreams].reverse().map((dream) => ({
		date: new Date(dream.date).toLocaleDateString(),
		sleep: dream.sleepAmount,
	}));

	return (
		<div class="left-padding">
			<h1>Your Dream Notebook</h1>
			{dreams.length === 0 ? (
				<div>
					<p>No Dreams Found</p>
					<p>
						Click "Create Dream" in the top right to log your first
						dream!
					</p>
				</div>
			) : (
				<>
					<button
						className="del-dream-bttn"
						onClick={() => setShowStats(!showStats)}
					>
						{showStats ? "Hide Stats" : "View Stats"}
					</button>
					<br />
					{showStats && (
						<div className="view-dream-container">
							<p>
								<strong>Total Dreams:</strong> {totalDreams}
							</p>
							<p>
								<strong>Total Sleep Time:</strong> {totalSleep}{" "}
								hours
							</p>
							<p>
								<strong>Average Sleep per Dream:</strong>{" "}
								{avgSleep.toFixed(2)} hours
							</p>
							<div style={{ width: "100%", height: 300 }}>
								{/* This chart was made with recharts: https://recharts.org/en-US */}
								<ResponsiveContainer>
									<AreaChart
										data={chartData}
										width="80%"
										length="80%"
									>
										<CartesianGrid strokeDasharray="5 5" />
										<XAxis dataKey="date" />
										<YAxis
											domain={[0, 12]}
											label={{
												value: "Hours",
												angle: -90,
												position: "insideLeft",
											}}
										/>
										<Tooltip />
										<Area
											type="monotone"
											dataKey="sleep"
											stroke="#b020f7"
											fill="#b020f7"
											strokeWidth={2}
											fillOpacity={0.3}
										/>
									</AreaChart>
								</ResponsiveContainer>
							</div>
						</div>
					)}

					{dreams.map((dream) => (
						<div
							key={dream.nightId}
							className="view-dream-container"
						>
							<p>
								<div className="dream-markdown">
									<strong>Dream:</strong>{" "}
									<ReactMarkdown breaks>
										{dream.dreamEntry}
									</ReactMarkdown>
								</div>
							</p>
							<p>
								<strong>Slept:</strong> {dream.sleepAmount}{" "}
								hours
							</p>
							<p>
								<strong>Date:</strong>{" "}
								{dayjs(dream.date).format("M/D/YYYY")}
							</p>
							<button
								className="del-dream-bttn"
								onClick={() => deleteDream(dream._id)}
							>
								Delete
							</button>
						</div>
					))}
				</>
			)}
		</div>
	);
}

export default ViewDreams;
